url: https://qwelias.me

theme: jekyll-theme-midnight

site-css:
  - /assets/css/custom-styles.css

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

exclude:
  - CNAME
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-sitemap
