name: Ilia Baryshnikov
description:
url: https://qwelias.me
title: Ilia Baryshnikov
author: Ilia Baryshnikov

theme: jekyll-theme-midnight

navbar-links:
  CV: "cv"
  noise: "noise"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
